In [1]:
import requests
import lxml.html as lh
import pandas as pd

In [2]:
url='https://en.wikipedia.org/wiki/List_of_postal_codes_of_Canada:_M'
#Create a handle, page, to handle the contents of the website
page = requests.get(url)
#Store the contents of the website under doc
doc = lh.fromstring(page.content)
#Parse data that are stored between <tr>..</tr> of HTML
tr_elements = doc.xpath('//tr')

In [3]:
#Check the length of the first 12 rows
[len(T) for T in tr_elements[:12]]

[3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]

In [5]:
tr_elements = doc.xpath('//tr')
#Create empty list
col=[]
i=0
#For each row, store each first element (header) and an empty list
for t in tr_elements[0]:
    i+=1
    name=t.text_content()
    print ('%d:"%s"'%(i,name))
    col.append((name,[]))

1:"Postal Code
"
2:"Borough
"
3:"Neighborhood
"

In [6]:
for j in range(1,len(tr_elements)):
    #T is our j'th row
    T=tr_elements[j]
    
    #If row is not of size 3, the //tr data is not from our table 
    if len(T)!=3:
        break
    
    #i is the index of our column
    i=0
    
    #Iterate through each element of the row
    for t in T.iterchildren():
        data=t.text_content() 
        #Check if row is empty
        if i>0:
        #Convert any numerical value to integers
            try:
                data=int(data)
            except:
                pass
        #Append the data to the empty list of the i'th column
        col[i][1].append(data)
        #Increment i for the next column
        i+=1

In [7]:
[len(C) for (title,C) in col]

[181, 181, 181]

In [8]:
Dict={title:column for (title,column) in col}
df=pd.DataFrame(Dict)

In [9]:
df.head()

  Postal Code\n           Borough\n               Neighborhood\n
0         M1A\n      Not assigned\n               Not assigned\n
1         M2A\n      Not assigned\n               Not assigned\n
2         M3A\n        North York\n                  Parkwoods\n
3         M4A\n        North York\n           Victoria Village\n
4         M5A\n  Downtown Toronto\n  Regent Park, Harbourfront\n

In [12]:
df.head()

  Postal Code\n           Borough\n               Neighborhood\n
0         M1A\n      Not assigned\n               Not assigned\n
1         M2A\n      Not assigned\n               Not assigned\n
2         M3A\n        North York\n                  Parkwoods\n
3         M4A\n        North York\n           Victoria Village\n
4         M5A\n  Downtown Toronto\n  Regent Park, Harbourfront\n

In [13]:
df.columns = df.columns.str.rstrip('\n')  # strip suffix at the right end only.

df.columns

Index(['Postal Code', 'Borough', 'Neighborhood'], dtype='object')

In [16]:
df = df.applymap(lambda x: str(x).rstrip('\n'))

df

,Postal Code,Borough,Neighborhood
0,M1A,Not assigned,Not assigned
1,M2A,Not assigned,Not assigned
2,M3A,North York,Parkwoods
3,M4A,North York,Victoria Village
4,M5A,Downtown Toronto,"Regent Park, Harbourfront"
...,...,...,...
176,M6Z,Not assigned,Not assigned
177,M7Z,Not assigned,Not assigned
178,M8Z,Etobicoke,"Mimico NW, The Queensway West, South of Bloor,..."
179,M9Z,Not assigned,Not assigned
180,,Canadian postal codes,

In [18]:
import numpy as np
df = df.replace('Not assigned',np.nan)

In [19]:
df.apply(lambda x: sum(x.isnull()))

Postal Code      0
Borough         77
Neighborhood    77
dtype: int64

In [24]:
df_assigned = df.dropna(how = 'any',subset=['Borough'])

In [25]:
df_assigned

,Postal Code,Borough,Neighborhood
2,M3A,North York,Parkwoods
3,M4A,North York,Victoria Village
4,M5A,Downtown Toronto,"Regent Park, Harbourfront"
5,M6A,North York,"Lawrence Manor, Lawrence Heights"
6,M7A,Downtown Toronto,"Queen's Park, Ontario Provincial Government"
...,...,...,...
165,M4Y,Downtown Toronto,Church and Wellesley
168,M7Y,East Toronto,"Business reply mail Processing Centre, South C..."
169,M8Y,Etobicoke,"Old Mill South, King's Mill Park, Sunnylea, Hu..."
178,M8Z,Etobicoke,"Mimico NW, The Queensway West, South of Bloor,..."
180,,Canadian postal codes,

In [26]:
df.head(50)

,Postal Code,Borough,Neighborhood
0,M1A,NaN,NaN
1,M2A,NaN,NaN
2,M3A,North York,Parkwoods
3,M4A,North York,Victoria Village
4,M5A,Downtown Toronto,"Regent Park, Harbourfront"
5,M6A,North York,"Lawrence Manor, Lawrence Heights"
6,M7A,Downtown Toronto,"Queen's Park, Ontario Provincial Government"
7,M8A,NaN,NaN
8,M9A,Etobicoke,"Islington Avenue, Humber Valley Village"
9,M1B,Scarborough,"Malvern, Rouge"
10,M2B,NaN,NaN
11,M3B,North York,Don Mills
12,M4B,East York,"Parkview Hill, Woodbine Gardens"
13,M5B,Downtown Toronto,"Garden District, Ryerson"
14,M6B,North York,Glencairn
15,M7B,NaN,NaN
16,M8B,NaN,NaN
17,M9B,Etobicoke,"West Deane Park, Princess Gardens, Martin Grov..."
18,M1C,Scarborough,"Rouge Hill, Port Union, Highland Creek"
19,M2C,NaN,NaN
20,M3C,North York,Don Mills
21,M4C,East York,Woodbine Heights
22,M5C,Downtown Toronto,St. James Town
23,M6C,York,Humewood-Cedarvale
24,M7C,NaN,NaN
25,M8C,NaN,NaN
26,M9C,Etobicoke,"Eringate, Bloordale Gardens, Old Burnhamthorpe..."
27,M1E,Scarborough,"Guildwood, Morningside, West Hill"
28,M2E,NaN,NaN
29,M3E,NaN,NaN
30,M4E,East Toronto,The Beaches
31,M5E,Downtown Toronto,Berczy Park
32,M6E,York,Caledonia-Fairbanks
33,M7E,NaN,NaN
34,M8E,NaN,NaN
35,M9E,NaN,NaN
36,M1G,Scarborough,Woburn
37,M2G,NaN,NaN
38,M3G,NaN,NaN
39,M4G,East York,Leaside
40,M5G,Downtown Toronto,Central Bay Street
41,M6G,Downtown Toronto,Christie
42,M7G,NaN,NaN
43,M8G,NaN,NaN
44,M9G,NaN,NaN
45,M1H,Scarborough,Cedarbrae
46,M2H,North York,Hillcrest Village
47,M3H,North York,"Bathurst Manor, Wilson Heights, Downsview North"
48,M4H,East York,Thorncliffe Park
49,M5H,Downtown Toronto,"Richmond, Adelaide, King"

In [27]:
df_assigned['Postal Code'].value_counts()

M5B    1
M4L    1
M5W    1
M4N    1
M5P    1
      ..
M3B    1
M5G    1
M8Z    1
M8W    1
       1
Name: Postal Code, Length: 104, dtype: int64

In [28]:
df_assigned = df_assigned.drop([180],axis=0)

In [29]:
df_assigned

,Postal Code,Borough,Neighborhood
2,M3A,North York,Parkwoods
3,M4A,North York,Victoria Village
4,M5A,Downtown Toronto,"Regent Park, Harbourfront"
5,M6A,North York,"Lawrence Manor, Lawrence Heights"
6,M7A,Downtown Toronto,"Queen's Park, Ontario Provincial Government"
...,...,...,...
160,M8X,Etobicoke,"The Kingsway, Montgomery Road, Old Mill North"
165,M4Y,Downtown Toronto,Church and Wellesley
168,M7Y,East Toronto,"Business reply mail Processing Centre, South C..."
169,M8Y,Etobicoke,"Old Mill South, King's Mill Park, Sunnylea, Hu..."
178,M8Z,Etobicoke,"Mimico NW, The Queensway West, South of Bloor,..."